# Generated by Django 4.1.2 on 2022-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_id", models.CharField(max_length=50)),
                ("thumbnail", models.ImageField(upload_to="thumbnail/%Y/%m/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tech-talks", "Tech Talks"),
                            ("freelancing", "Freelancing"),
                            ("content-creation", "Content Creations"),
                            ("finance", "Finance"),
                            ("entrepreneurship", "Entrepreneurship"),
                        ],
                        max_length=100,
                    ),
                ),
                ("scheduled_on", models.DateTimeField()),
            ],
        ),
    ]
