# Generated by Django 4.1.2 on 2022-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_profile'),
        ('events', '0002_event_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='hashtags.hashtag'),
        ),
    ]
