# Generated by Django 4.1.2 on 2022-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0003_alter_profile_hashtags_followed_feedback'),
        ('events', '0003_alter_event_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='hashtags.hashtag'),
        ),
    ]
